dist: trusty
sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 7.2
- 7.3
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 12
- npm install
- npm rebuild node-sass
- composer install
script:
- npm run build
- composer test
after_success:
- pwd
- ls -al
before_deploy:
- npm run build
- ls -al
- npm run zip
- ls -la snow-monkey-design-skin-hakuji.zip
- export RELEASE_FILE=$(ls snow-monkey-design-skin-hakuji.zip)
deploy:
  provider: releases
  api_key:
    secure: h0wAENN+88QNkN+8E8WY7lpaBZtSd+98KgY119ZB8PH4gijM6Z65miWh+i+5Sg9718DgFi5o8lBv/gLIhhvzdiDpwGwW4tLb9uOgG9EWR1pbThcJXUghvtnSQrefFrasFt2PykXgogoMXHQ+0UspozXEWi1OUNylJTiQpwf/vyoNnpDtTliatelq9Ao9eqwbcu6wN3r1yTvMP+TV6U6H2p1fm7vts8OZq/UhzMdsrQCnpJQ8BTYFa//x016B9W+2+Zw4R+T7N6PFQdXSPAesU4aYSg6VsXtbur+qNreiOEz8Stfe2TCIdkOvL48ys8AcnAjUpWgElRak+Q87sv/9M6e1CrlOrR9oJ/sd/POonuNsoP5x2wm23Dyk+3qUVhdroiovfPQN+xdpVz2XE/EZ4HJoZ2muN3jNCEhDbqirJ/vXkLaWZsPyOkSK0b2gU2CclhTxkz21/gU0N/YEzYQRqX2ilAEeOQok6EnHmKjeHWz8jnKlV7WosI+MBgg7fu0XjdINhlu7gvPVl87nJf8jqQtpX6UiiR0OeJFFAd96iTeCL3atR+MMax/XiGaG0UbYOuovfcWFN374MLFrIxOhCSx0ag/QXzzXjv4NYMIjst4RP51bXP3bunIFSxQnKZ2VLoUASDe+0qnDpyGY8nB4uApkPk/G7j1KZLbtmo2MJeQ=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: inc2734/snow-monkey-design-skin-hakuji
    php: 7.2
